on:
  push:
    branches: ["staging"]
name: Staging Release
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: staging-${{ steps.date.outputs.date }}-${{ github.sha }}
          release_name: Staging Release ${{ steps.date.outputs.date }}
          draft: false
          prerelease: true
